# Generated by Django 3.0.7 on 2020-07-15 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attentionTo', models.CharField(max_length=50)),
                ('companyName', models.CharField(max_length=50)),
                ('line1', models.CharField(max_length=50)),
                ('line2', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='award',
            name='award_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='member',
            name='_id',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='award',
        ),
        migrations.AddField(
            model_name='shipment',
            name='award',
            field=models.ManyToManyField(to='tracking.Award'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.Address'),
        ),
    ]
