# Generated by Django 3.0.7 on 2020-07-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20200715_0103'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shipment',
        ),
    ]
